name: Autodeploy to GH-Pages

on:  
 push:
    branches:    
      - nuxt
      - master 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and deploy to gh-pages
      run: |
        cd site
        yarn install
        yarn run generate:gh-pages
        remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        remote_branch="gh-pages"
        git config --global user.email "git@coin-history.com"
        git config --global user.name "Coin-History Autocommit"
        git add -A
        git commit -m "action build"
        yarn run deploy:gh-pages
        rm -fr .git
      env:
        CI: true
